### ISSUE TITLE
when implementing your own http request handler you should check Moodle proxy settings

### ISSUE THREAD

**Issue by danmarsden** [cperves/moodle-repository_pod#2]
When implementing your own request handler (like guzzle) instead of using the Moodle core curl class and other libraries, you should be including 

Guzzle is quite handy, but many moodle sites sit behind a web proxy and so the admin can configure this under admin > server > HTTP > Web proxy settings

Ideally you should check if $CFG->proxyhost is not empty and use it in your guzzle requests (along with proxyport/user/pass set in admin)

Note: this probably isn't a blocker for approval, but you if you don't fix this we'd want to make sure this is documented in your readme - (support for web proxy not included).

**Comment by cperves** [comment]
I should better use moodle standard then

**Comment by cperves** [comment]
Thank you for the advide
